name: gestion_formation_app
description: Frontend Flutter pour plateforme de formation interne
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  syncfusion_flutter_pdfviewer: ^24.1.41   # vérifiez la dernière version

flutter:
  uses-material-design: true
